-- MySQL Script generated by MySQL Workbench
-- Wed Jul  1 22:57:43 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`raca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`raca` (
  `id_raca` INT NOT NULL AUTO_INCREMENT,
  `nome_raca` VARCHAR(90) NOT NULL,
  `porte` ENUM('Pequeno', 'Medio', 'Grande') NOT NULL,
  PRIMARY KEY (`id_raca`),
  UNIQUE INDEX `nome_raca_UNIQUE` (`nome_raca` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cavalo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cavalo` (
  `id_cavalo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  `status` ENUM('Ativo', 'Vendido', 'Óbito', 'Em tratamento') NOT NULL,
  `origem` ENUM('Próprio', 'Externo') NOT NULL,
  `sexo` ENUM('M', 'F') NOT NULL,
  `dt_nasc` DATE NULL,
  `cor` VARCHAR(45) NULL,
  `peso` DECIMAL(5,2) NULL,
  `altura` DECIMAL(4,2) NULL,
  `raca_id_raca` INT NULL,
  `mae_id_cavalo` INT NULL,
  `pai_id_cavalo` INT NULL,
  PRIMARY KEY (`id_cavalo`),
  INDEX `fk_cavalo_raca1_idx` (`raca_id_raca` ASC) VISIBLE,
  INDEX `fk_cavalo_cavalo1_idx` (`mae_id_cavalo` ASC) VISIBLE,
  INDEX `fk_cavalo_cavalo2_idx` (`pai_id_cavalo` ASC) VISIBLE,
  CONSTRAINT `fk_cavalo_raca1`
    FOREIGN KEY (`raca_id_raca`)
    REFERENCES `mydb`.`raca` (`id_raca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cavalo_cavalo1`
    FOREIGN KEY (`mae_id_cavalo`)
    REFERENCES `mydb`.`cavalo` (`id_cavalo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cavalo_cavalo2`
    FOREIGN KEY (`pai_id_cavalo`)
    REFERENCES `mydb`.`cavalo` (`id_cavalo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoa` (
  `id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `cpf` CHAR(11) NOT NULL,
  `nome` VARCHAR(90) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  PRIMARY KEY (`id_pessoa`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `pessoa_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_cliente_pessoa1_idx` (`pessoa_id_pessoa` ASC) VISIBLE,
  UNIQUE INDEX `pessoa_id_pessoa_UNIQUE` (`pessoa_id_pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_pessoa1`
    FOREIGN KEY (`pessoa_id_pessoa`)
    REFERENCES `mydb`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`baia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`baia` (
  `id_baia` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(10) NOT NULL,
  `status` ENUM('Livre', 'Ocupada') NOT NULL,
  `tamanho` ENUM('P', 'M', 'G') NOT NULL,
  PRIMARY KEY (`id_baia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cargo` (
  `id_cargo` INT NOT NULL AUTO_INCREMENT,
  `nome_cargo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_cargo`),
  UNIQUE INDEX `nome_cargo_UNIQUE` (`nome_cargo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `salario` DECIMAL(10,2) NOT NULL,
  `pessoa_id_pessoa` INT NOT NULL,
  `cargo_id_cargo` INT NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  INDEX `fk_funcionario_pessoa_idx` (`pessoa_id_pessoa` ASC) VISIBLE,
  INDEX `fk_funcionario_cargo1_idx` (`cargo_id_cargo` ASC) VISIBLE,
  UNIQUE INDEX `pessoa_id_pessoa_UNIQUE` (`pessoa_id_pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_pessoa`
    FOREIGN KEY (`pessoa_id_pessoa`)
    REFERENCES `mydb`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_cargo1`
    FOREIGN KEY (`cargo_id_cargo`)
    REFERENCES `mydb`.`cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `data_venda` DATETIME NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  `cavalo_id_cavalo` INT NOT NULL,
  `funcionario_id_funcionario` INT NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_venda_cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  INDEX `fk_venda_cavalo1_idx` (`cavalo_id_cavalo` ASC) VISIBLE,
  INDEX `fk_venda_funcionario1_idx` (`funcionario_id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_cavalo1`
    FOREIGN KEY (`cavalo_id_cavalo`)
    REFERENCES `mydb`.`cavalo` (`id_cavalo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_funcionario1`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `mydb`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`baia_historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`baia_historico` (
  `id_baia_historico` INT NOT NULL AUTO_INCREMENT,
  `data_entrada` DATETIME NOT NULL,
  `data_saida` DATETIME NULL,
  `baia_id_baia` INT NOT NULL,
  `cavalo_id_cavalo` INT NOT NULL,
  PRIMARY KEY (`id_baia_historico`),
  INDEX `fk_baia_historico_baia1_idx` (`baia_id_baia` ASC) VISIBLE,
  INDEX `fk_baia_historico_cavalo1_idx` (`cavalo_id_cavalo` ASC) VISIBLE,
  CONSTRAINT `fk_baia_historico_baia1`
    FOREIGN KEY (`baia_id_baia`)
    REFERENCES `mydb`.`baia` (`id_baia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_baia_historico_cavalo1`
    FOREIGN KEY (`cavalo_id_cavalo`)
    REFERENCES `mydb`.`cavalo` (`id_cavalo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;